name: build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build Linux
      run: GOOS=linux go build -v ./...

    - name: Build Windows
      run: GOOS=windows go build -v ./...
---
name: pre-release

on:
  push:
    branches: [ master ]

jobs:
  pre-release:
    name: Pre Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build Linux
      run: GOOS=linux go build -v ./...

    - name: Build Windows
      run: GOOS=windows go build -v ./...
    
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          binarysearch
          binarysearch.exe
          scan_folder_for_binary.sh
          scan_git_repo_for_binary.sh

---
name: tagged-release

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: Tagged Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build Linux
      run: GOOS=linux go build -v ./...

    - name: Build Windows
      run: GOOS=windows go build -v ./...
    
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          binarysearch
          binarysearch.exe
          scan_folder_for_binary.sh
          scan_git_repo_for_binary.sh
